modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="jej" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Just Enough Juices" #mandatory
logoFile="logo.png" #optional
credits="Thanks for Downloading Just Enough Juice.. :D" #optional
authors="Love, Cheese Ez" #optional
description='''
Just Enough Juice Mod Add Varies Types Of juices To Minecraft Mod
That Gives You Effects
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.20)"
    ordering="NONE"
    side="BOTH"
